Block 4: Modals
codedit334/Portfolio_Microverse pull request #10
Opened 2023-01-31 21:17 UTC by codedit334

Created a functional modal using vanilla Javascript:
1. Create modal windows using HTML and CSS
2. Add functionnality to it using JS: Itcan show and hide

2023-01-31 22:17 UTC, laiifuu commented on index.js
> +];
Nice work using an array of objects to store the projects data :clap: :clap: However, the link to the source code and the link to the live demo are missing. I suggest adding them for each object.

2023-01-31 22:50 UTC, laiifuu reviewed
## Hi team :wave: 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project where you disabled JavaScript linters using `/* eslint-disable no-unused-vars */`

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-02-01 08:07 UTC, Olamarx requested changes
Hi @codedit334,

Good job so far, indeed you have spent time on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media1.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif"/>

## Highlights
- Linters passed ✔️
- popup functionality ✔️ 

## Required Changes ♻️
_Check the comments under the review._
- [ ] I would advise you to remove the whole work section and add it dynamically with javascript just as you did for the modal where you have the data in an array and you iterate over it. This is one of the requirements.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-01 08:07 UTC, Olamarx commented on index.js
> +modal.forEach((o) => {
- [ ] What do you mean by `o` here? It is of best practice to use meaningful words so that they could be understood by even a day-old coder.

2023-02-01 08:21 UTC, merged